# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GBSHOP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GBSHOP
pod 'Swinject'
pod 'Alamofire'
  target 'GBSHOPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GBSHOPUITests' do
    # Pods for testing
  end

end
